CREATE TABLE `coins` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `EXECID` varchar(45) DEFAULT NULL,
  `EMI` varchar(25) DEFAULT NULL,
  `REFER` varchar(20) DEFAULT NULL,
  `EXCHANGE` varchar(20) DEFAULT NULL,
  `CURRENCY` varchar(10) DEFAULT NULL,
  `SYMBOL` varchar(20) DEFAULT NULL,
  `CATEGORY` varchar(10) DEFAULT NULL,
  `SIDE` tinyint DEFAULT NULL,
  `QTY` int DEFAULT NULL,
  `QTY_REST` int DEFAULT NULL,
  `PRICE` decimal(16,8) DEFAULT NULL,
  `THEOR_PRICE` decimal(16,8) DEFAULT NULL,
  `TRADE_PRICE` decimal(16,8) DEFAULT NULL,
  `SUMREAL` decimal(19,12) DEFAULT NULL,
  `COMMISS` decimal(19,15) DEFAULT '0.000000000000000',
  `TTIME` datetime DEFAULT NULL,
  `DAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CLORDID` int DEFAULT '0',
  `ACCOUNT` int DEFAULT '0',
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `EXECID_ix` (`EXECID`),
  KEY `EMI_QTY_ix` (`EMI`,`QTY`),
  KEY `SIDE_ix` (`SIDE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `robots` (
  `EMI` varchar(20) DEFAULT NULL,
  `SYMBOL` varchar(20) DEFAULT NULL,
  `CATEGORY` varchar(10) DEFAULT NULL,
  `EXCHANGE` varchar(20) DEFAULT NULL,
  `SORT` tinyint DEFAULT NULL,
  `DAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `TIMEFR` tinyint DEFAULT '0',
  `CAPITAL` int DEFAULT '0',
  `MARGIN` int DEFAULT '0'
  UNIQUE KEY `EMI_UNIQUE` (`EMI`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
