from enum import Enum


class ErrorStatus(Enum):
    RETRY = {
        10000: "Server Timeout",
        10002: "The request time exceeds the time window range.",
        10016: "Server error.",
        110063: "Settlement in progress! {{key0}} not available for trading.",
        110079: "The order is processing and can not be operated, please try again later",
        3400214: "Server error, please try again later",
        170001: "Internal error.",
        170032: "Network error. Please try again later",
        170191: "Can not cancel order, please try again later",
    }
    FATAL = {
        10016: "1. internal server error; 2. Service is restarting",
        10019: "ws trade service is restarting, do not accept new request, but the request in the process is not affected. You can build new connection to be routed to normal service",
        170234: "System Error",
    }
    BLOCK = {
        10027: "Transactions are banned.",
        110004: "Wallet balance is insufficient",
        110006: "The assets are estimated to be unable to cover the position margin",
        110007: "Available balance is insufficient",
        110012: "Insufficient available balance.",
        110013: "Cannot set leverage due to risk limit level.",
        110014: "Insufficient available balance to add additional margin.",
        110015: "The position is in cross margin mode.",
        110045: "Wallet balance is insufficient.",
        110052: "Your available balance is insufficient to set the price",
        110053: "The user's available balance cannot cover the current market price and upper limit price",
        110069: "Ins lending customer is not allowed to trade.",
        110080: "Operations Restriction: The current LTV ratio of your Institutional Lending has hit the liquidation threshold. Assets in your account are being liquidated (trade/risk limit/leverage)",
        110088: "Please Upgrade to UTA to trade",
        170033: "margin Insufficient account balance",
        170226: "Your Spot Account for Margin Trading is being liquidated.",
        176015: "Insufficient available balance",
    }
    IGNORE = {
        10404: "1. op type is not found; 2. category is not correct/supported",
        10429: "System level frequency protection",
        20006: "reqId is duplicated",
        10003: "Too many sessions under the same UID",
        10001: "Request parameter error",
        10014: "Invalid duplicate request.",
        10024: "Compliance rules triggered",
        10029: "The requested symbol is invalid, please check symbol whitelist",
        30133: "OTC loan: The symbol you select for USDT Perpetual is not allowed by Institutional Lending",
        30134: "OTC loan: The symbol you select for USDC Contract is not allowed by Institutional Lending",
        30135: "The leverage you select for USDT Perpetual trading cannot exceed the maximum leverage allowed by Institutional Lending.",
        30136: "The leverage you select for USDC Perpetual or Futures trading cannot exceed the maximum leverage allowed by Institutional Lending.",
        40004: "the order is modified during the process of replacing , please check the order status again",
        110001: "Order does not exist",
        110003: "Order price exceeds the allowable range.",
        110005: "position status",
        110008: "The order has been completed or cancelled.",
        110009: "The number of stop orders exceeds the maximum allowable limit. You can find references in our API doc.",
        110010: "The order has been cancelled",
        110011: "Liquidation will be triggered immediately by this adjustment",
        110017: "Reduce-only rule not satisfied",
        110019: "Order ID is illegal.",
        110020: "Not allowed to have more than 500 active orders.",
        110021: "Not allowed to exceeded position limits due to Open Interest.",
        110022: "Quantity has been restricted and orders cannot be modified to increase the quantity.",
        110023: "Currently you can only reduce your position on this contract. please check our announcement or contact customer service for details.",
        110024: "You have an existing position, so the position mode cannot be switched.",
        110025: "Position mode has not been modified.",
        110026: "Cross/isolated margin mode has not been modified.",
        110027: "Margin has not been modified.",
        110028: "You have existing open orders, so the position mode cannot be switched.",
        110029: "Hedge mode is not supported for this symbol.",
        110031: "Non-existing risk limit info, please check the risk limit rules.",
        110032: "Order is illegal",
        110033: "You can't set margin without an open position",
        110034: "There is no net position",
        110035: "Cancellation of orders was not completed before liquidation",
        110036: "You are not allowed to change leverage due to cross margin mode.",
        110037: "User setting list does not have this symbol",
        110038: "You are not allowed to change leverage due to portfolio margin mode.",
        110039: "Maintenance margin rate is too high. This may trigger liquidation.",
        110040: "The order will trigger a forced liquidation, please re-submit the order.",
        110041: "Skip liquidation is not allowed when a position or maker order exists",
        110042: "Currently,due to pre-delivery status, you can only reduce your position on this contract.",
        110043: "Set leverage has not been modified.",
        110044: "Available margin is insufficient.",
        110046: "Liquidation will be triggered immediately by this adjustment.",
        110047: "Risk limit cannot be adjusted due to insufficient available margin.",
        110048: "Risk limit cannot be adjusted as the current/expected position value exceeds the revised risk limit.",
        110049: "Tick notes can only be numbers",
        110050: "Invalid coin",
        110051: "The user's available balance cannot cover the lowest price of the current market",
        110054: "This position has at least one take profit link order, so the take profit and stop loss mode cannot be switched",
        110055: "This position has at least one stop loss link order, so the take profit and stop loss mode cannot be switched",
        110056: "This position has at least one trailing stop link order, so the take profit and stop loss mode cannot be switched",
        110057: "Conditional order or limit order contains TP/SL related params",
        110058: "You can't set take profit and stop loss due to insufficient size of remaining position size.",
        110059: "Not allowed to modify the TP/SL of a partially filled open order",
        110060: "Under full TP/SL mode, it is not allowed to modify TP/SL",
        110061: "Not allowed to have more than 20 TP/SLs under Partial tpSlMode",
        110061: "Not allowed to have more than 20 TP/SLs under Partial tpSlMode",
        110062: "There is no MMP information of the institution found.",
        110064: "The modified contract quantity cannot be less than or equal to the filled quantity.",
        110065: "MMP hasn't yet been enabled for your account. Please contact your BD manager.",
        110066: "Trading is currently not allowed.",
        110068: "Leveraged trading is not allowed.",
        110070: "ETP symbols cannot be traded.",
        110071: "Sorry, we're revamping the Unified Margin Account! Currently, new upgrades are not supported. If you have any questions, please contact our 24/7 customer support.",
        110072: "OrderLinkedID is duplicate",
        110073: "Set margin mode failed",
        110075: "RiskId not modified",
        182021: "Cannot enable spot margin while in isolated margin mode. Please switch to cross margin mode or portfolio margin mode to trade spot with margin.",
        110076: "Only isolated mode can set auto-add-margin",
        110077: "Pm mode cannot support",
        110078: "Added margin more than max can reduce margin",
        110082: "You cannot lift Reduce-Only restrictions, as no Reduce-Only restrictions are applied to your position",
        110083: "Reduce-Only restrictions must be lifted for both Long and Short positions at the same time",
        110085: "The risk limit and margin ratio for this contract has been updated, please select a supported risk limit and place your order again",
        110086: "Current order leverage exceeds the maximum available for your current Risk Limit tier. Please lower leverage before placing an order",
        110087: "Leverage for Perpetual or Futures contracts cannot exceed the maximum allowed for your Institutional loan",
        110089: "Exceeds the maximum risk limit level",
        110090: "Exceeds the maximum leverage limit of the current risk limit level.",
        110092: "expect Rising, but trigger_price[XXXXX] <= current[XXXXX]??laste",
        110093: "expect Falling, but trigger_price[XXXXX] >= current[XXXXX]??last",
        110094: "Order notional value below the lower limit",
        110095: "You cannot create, modify or cancel Pre-Market Perpetual orders during the Call Auction.",
        110096: "Pre-Market Perpetual Trading does not support Portfolio Margin mode.",
        110097: "Non-UTA users cannot access Pre-Market Perpetual Trading. To place, modify or cancel Pre-Market Perpetual orders, please upgrade your Standard Account to UTA.",
        110098: "Only Good-Till-Canceled (GTC) orders are supported during Call Auction.",
        110099: "You cannot create TP/SL orders during the Call Auction for Pre-Market Perpetuals.",
        110100: "You cannot place, modify, or cancel Pre-Market Perpetual orders when you are in Demo Trading.",
        110101: "Trading inverse contracts under Cross and Portfolio modes requires enabling the settlement asset as collateral.",
        110102: "The user does not support trading Inverse contracts - copy trading pro, Ins loan account are not supported",
        181017: "OrderStatus must be final status",
        182100: "Compulsory closing of positions, no repayment allowed",
        182101: "Failed repayment, insufficient collateral balance",
        182102: "Failed repayment, there are no liabilities in the current currency",
        182103: "Institutional lending users are not supported",
        182108: "Switching failed, margin verification failed, please re-adjust the currency status",
        182110: "Failed to switch",
        182111: "The requested currency has a non guaranteed gold currency or does not support switching status currencies",
        182112: "Duplicate currency, please re-adjust",
        3100181: "UID can not be null",
        3100197: "Temporary banned due to the upgrade to UTA",
        3200316: "USDC Options Trading Restriction: The current LTV ratio for your Institutional Lending has reached the maximum allowable amount for USDC Options trading.",
        3200317: "USDC Options Open Position Restriction: The current LTV ratio for your Institutional Lending has reached the maximum allowable amount for opening USDC Options positions.",
        3100326: "BaseCoin is required",
        3200403: "isolated margin can not create order",
        3200419: "Unable to switch to Portfolio margin due to active pre-market Perpetual orders and positions",
        3200320: "Operations Restriction: The current LTV ratio of your Institutional Lending has hit the liquidation threshold. Assets in your account are being liquidated. (margin mode or spot leverage)",
        3400208: "You have unclosed hedge mode or isolated mode USDT perpetual positions",
        3400209: "You have USDT perpetual positions, so upgrading is prohibited for 10 minutes before and after the hour every hour",
        3400210: "The risk rate of your Derivatives account is too high",
        3400211: "Once upgraded, the estimated risk rate will be too high",
        3400212: "You have USDC perpetual positions or Options positions, so upgrading is prohibited for 10 minutes before and after the hour every hour",
        3400213: "The risk rate of your USDC Derivatives account is too high",
        3400052: "You have uncancelled USDC perpetual orders",
        3400053: "You have uncancelled Options orders",
        3400054: "You have uncancelled USDT perpetual orders",
        3400071: "The net asset is not satisfied",
        3401010: "Cannot switch to PM mode (for copy trading master trader)",
        3400139: "The total value of your positions and orders has exceeded the risk limit for a Perpetual or Futures contract",
        500010: "The sub-account specified does not belong to the parent account",
        500011: "The Uid 592334 provided is not associated with a Unified Trading Account",
        170005: "Too many new orders; current limit is %s orders per %s.",
        170007: "Timeout waiting for response from backend server.",
        170010: "Purchase failed: Exceed the maximum position limit of leveraged tokens, the current available limit is %s USDT",
        170011: "Purchase failed: Exceed the maximum position limit of innovation tokens,",
        170019: "the current available limit is ''{{.replaceKey0}}'' USDT",
        170031: "The feature has been suspended",
        170034: "Liability over flow in spot leverage trade!",
        170035: "Submitted to the system for processing!",
        170036: "You haven't enabled Cross Margin Trading yet. To do so, please head to the PC trading site or the Bybit app",
        170037: "Cross Margin Trading not yet supported by the selected coin",
        170105: "Parameter '%s' was empty.",
        170115: "Invalid timeInForce.",
        170116: "Invalid orderType.",
        170117: "Invalid side.",
        170121: "Invalid symbol.",
        170124: "Order amount too large.",
        170130: "Data sent for paramter '%s' is not valid.",
        170131: "Balance insufficient",
        170132: "Order price too high.",
        170133: "Order price lower than the minimum.",
        170134: "Order price decimal too long.",
        170135: "Order quantity too large.",
        170136: "Order quantity lower than the minimum.",
        170137: "Order volume decimal too long",
        170139: "Order has been filled.",
        170140: "Transaction amount lower than the minimum.",
        170141: "Duplicate clientOrderId",
        170142: "Order has been canceled",
        170143: "Cannot be found on order book",
        170144: "Order has been locked",
        170145: "This order type does not support cancellation",
        170146: "Order creation timeout",
        170147: "Order cancellation timeout",
        170148: "Market order amount decimal too long",
        170149: "Create order failed",
        170150: "Cancel order failed",
        170151: "The trading pair is not open yet",
        170157: "The trading pair is not available for api trading",
        170159: "Market Order is not supported within the first %s minutes of newly launched pairs due to risk control.",
        170190: "Cancel order has been finished",
        170192: "Order price cannot be higher than %s .",
        170193: "Buy order price cannot be higher than %s.",
        170194: "Sell order price cannot be lower than %s.",
        170195: "Please note that your order may not be filled. ETP buy order price deviates from risk control",
        170196: "Please note that your order may not be filled. ETP sell order price deviates from risk control",
        170197: "Your order quantity to buy is too large. The filled price may deviate significantly from the market price. Please try again",
        170198: "Your order quantity to sell is too large. The filled price may deviate significantly from the market price. Please try again",
        170199: "Your order quantity to buy is too large. The filled price may deviate significantly from the nav. Please try again.",
        170200: "Your order quantity to sell is too large. The filled price may deviate significantly from the nav. Please try again.",
        170201: "Invalid orderFilter parameter",
        170202: "Please enter the TP/SL price.",
        170203: "trigger price cannot be higher than 110% price.",
        170204: "trigger price cannot be lower than 90% of qty.",
        170206: "Stop_limit Order is not supported within the first 5 minutes of newly launched pairs",
        170207: "The loan amount of the platform is not enough.",
        170210: "New order rejected.",
        170212: "Cancel order request processing",
        170213: "Order does not exist.",
        170215: "Spot Trading (Buy) Restriction: The current LTV ratio of your institutional lending has reached the maximum allowable amount for buy orders",
        170216: "The leverage you select for Spot Trading cannot exceed the maximum leverage allowed by Institutional Lending",
        170217: "Only LIMIT-MAKER order is supported for the current pair.",
        170218: "The LIMIT-MAKER order is rejected due to invalid price.",
        170219: "UID {{xxx}} is not available to this feature",
        170220: "Spot Trading Restriction: The current LTV ratio of your institutional lending has reached the maximum allowable amount for Spot trading",
        170221: "This coin does not exist.",
        170222: "Too many requests in this time frame.",
        170223: "Your Spot Account with Institutional Lending triggers an alert or liquidation.",
        170224: "You're not a user of the Innovation Zone.",
        170227: "This feature is not supported.",
        170228: "The purchase amount of each order exceeds the estimated maximum purchase amount.",
        170229: "The sell quantity per order exceeds the estimated maximum sell quantity.",
        170230: "Operations Restriction: Due to the deactivation of Margin Trading for institutional loan",
        170241: "To proceed with trading, users must read through and confirm that they fully understand the project's risk disclosure document. For App users, please update your Bybit App to version 4.16.0 to process.",
        170310: "Order modification timeout",
        170311: "Order modification failed",
        170312: "The current order does not support modification",
        170313: "The modified contract quantity cannot be less than to the filled quantity",
        170341: "Request order quantity exceeds maximum limit",
        170344: "Symbol is not supported on Margin Trading",
        170709: "OTC loan: The select trading pair is not in the whitelist pair",
        170810: "Cannot exceed maximum of 500 conditional, TP/SL and active orders.",
        175000: "The serialNum is already in use.",
        175001: "Daily purchase limit has been exceeded. Please try again later.",
        175002: "There's a large number of purchase orders. Please try again later.",
        175003: "Insufficient available balance. Please make a deposit and try again.",
        175004: "Daily redemption limit has been exceeded. Please try again later.",
        175005: "There's a large number of redemption orders. Please try again later.",
        175006: "Insufficient available balance. Please make a deposit and try again.",
        175007: "Order not found.",
        175008: "Purchase period hasn't started yet.",
        175009: "Purchase amount has exceeded the upper limit.",
        175010: "You haven't passed the quiz yet! To purchase and/or redeem an LT, please complete the quiz first.",
        175012: "Redemption period hasn't started yet.",
        175013: "Redemption amount has exceeded the upper limit.",
        175014: "Purchase of the LT has been temporarily suspended.",
        175015: "Redemption of the LT has been temporarily suspended.",
        175016: "Invalid format. Please check the length and numeric precision.",
        175017: "Failed to place order：Exceed the maximum position limit of leveraged tokens, the current available limit is XXXX USDT",
        175027: "Subscriptions and redemptions are temporarily unavailable while account upgrade is in progress",
        176002: "Query user account info error. Confirm that if you have completed quiz in GUI",
        176003: "Query user loan history error",
        176004: "Query order history start time exceeds end time",
        176005: "Failed to borrow",
        176006: "Repayment Failed",
        176007: "User not found",
        176008: "You haven't enabled Cross Margin Trading yet. To do so, please head to the PC trading site",
        176009: "You haven't enabled Cross Margin Trading yet. Confirm that if you have turned on margin trade",
        176010: "Failed to locate the coins to borrow",
        176011: "Cross Margin Trading not yet supported by the selected coin",
        176012: "Pair not available",
        176013: "Cross Margin Trading not yet supported by the selected pair",
        176014: "Repeated repayment requests",
        176016: "No repayment required",
        176017: "Repayment amount has exceeded the total liability",
        176018: "Settlement in progress",
        176019: "Liquidation in progress",
        176020: "Failed to locate repayment history",
        176021: "Repeated borrowing requests",
        176022: "Coins to borrow not generally available yet",
        176023: "Pair to borrow not generally available yet",
        176024: "Invalid user status",
        176025: "Amount to borrow cannot be lower than the min. amount to borrow (per transaction)",
        176026: "Amount to borrow cannot be larger than the max. amount to borrow (per transaction)",
        176027: "Amount to borrow cannot be higher than the max. amount to borrow per user",
        176028: "Amount to borrow has exceeded Bybit's max. amount to borrow",
        176029: "Amount to borrow has exceeded the user's estimated max. amount to borrow",
        176030: "Query user loan info error",
        176031: "Number of decimals for borrow amount has exceeded the maximum precision",
        176034: "The leverage ratio is out of range",
        176035: "Failed to close the leverage switch during liquidation",
        176036: "Failed to adjust leverage switch during forced liquidation",
        176037: "For non-unified transaction users, the operation failed",
        176038: "The spot leverage is closed and the current operation is not allowed",
        176039: "Borrowing, current operation is not allowed",
        176040: "There is a spot leverage order, and the adjustment of the leverage switch failed!",
        176132: "Number of decimals for repay amount has exceeded the maximum precision",
        176133: "Liquidation may be triggered! Please adjust your transaction amount and try again",
        176134: "Account has been upgraded (upgrading) to UTA",
        176135: "Failed to get bond data",
        176136: "Failed to get borrow data",
        176137: "Failed to switch user status",
        176138: "You need to repay all your debts before closing your disabling cross margin account",
        176139: "Sorry, you are not eligible to enable cross margin, as you have already enabled OTC lending",
        176201: "Account exception. Check if the UID is bound to an institutional loan",
        182104: "This action could not be completed as your Unified Margin Account's IM/MM utilization rate has exceeded the threshold",
        182105: "Adjustment failed, user is upgrading",
        182106: "Adjustment failed, user forced liquidation in progress.",
        182107: "Adjustment failed, Maintenance Margin Rate too high",
    }
    CANCEL = {
        # 400: "Bad request. Need to send the request with GET / POST (must be capitalized)",
        401: "Invalid request. 1. Need to use the correct key to access; 2. Need to put authentication params in the request header",
        403: "Forbidden request. Possible causes: 1. IP rate limit breached; 2. You send GET request with an empty json body; 3. You are using U.S IP",
        404: "Cannot find path. Possible causes: 1. Wrong path; 2. Category value does not match account mode",
        429: "System level frequency protection. Please retry when encounter this",
        10003: "API key is invalid. Check whether the key and domain are matched, there are 4 env: mainnet, testnet, mainnet-demo, testnet-demo",
        33004: "Your api key has expired",
        10004: "Error sign, please check your signature generation algorithm.",
        10005: "Permission denied, please check your API key permissions.",
        10006: "Too many visits. Exceeded the API Rate Limit.",
        10007: "User authentication failed.",
        10008: "Common banned, please check your account mode.",
        10009: "IP has been banned.",
        10010: "Unmatched IP, please check your API key's bound IP addresses.",
        10017: "Route not found.",
        10028: "The API can only be accessed by unified account users.",
        100028: "The API cannot be accessed by unified account users.",
        110018: "User ID is illegal.",
        110067: "Unified account is not supported.",
    }

    def status(error):
        error_number = error["error"]["code"]
        for status in ErrorStatus:
            if error_number in status.value:
                return status.name
